apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-staging
  namespace: demo
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "demo-staging.dryan.party"
